### ISSUE TITLE
Нужно табличное представление результатов ответов игроков

### ISSUE THREAD

**Issue by justvitalius** [justVitalius/quiz-telegram-bot#20]
Для задаче #16 нужен фронтенд.
Он должен представлять из себя одну страницу с таблицей
| username | firstName | lastName | secondName | category1 | category2 | ... |

В каждой категории следует выводить и общее число ответов и процент от numberOfNeedAnswers.

Исходники расположить в `src/statistics-ui`
В `package.json` создать задачку типа `build`

**Comment by w3dip** [comment]
Решил, что лепить все в один реп не стоит, сделал https://github.com/w3dip/statistics-ui

**Comment by justvitalius** [comment]
@w3dip добавь эту ссылку в readme проекта.
Чтобы не потерять.

**Comment by justvitalius** [comment]
Решено в другом репозитории
