### ISSUE TITLE
Ошибка при регистрации пользователя

### ISSUE THREAD

**Issue by GlebSa** [justVitalius/quiz-telegram-bot#38]
В телеграмме:
"Приветствую, undefined! Вы добавлены в список анкетирующихся. Через некоторое время вы получите вопрос."

В консоли:
start
TypeError: Cannot read property 'map' of undefined
    at messages.map (D:\Developments\JavaScript\quiz-telegram-bot\src\bot\index.js:59:38)
    at Array.map (<anonymous>)
    at processWaitingUsers.then.messages (D:\Developments\JavaScript\quiz-telegram-bot\src\bot\index.js:55:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Надо проверить, не частный ли это случай.

Объект msg (id замокал):
{ message_id: 93,
  from: 
   { id: 111111111,
     is_bot: false,
     first_name: 'Gleb',
     last_name: 'Sa',
     language_code: 'ru-RU' },
  chat: 
   { id: 111111111,
     first_name: 'Gleb',
     last_name: 'Sa',
     type: 'private' },
  date: 1524419560,
  text: '/start',
  entities: [ { offset: 0, length: 6, type: 'bot_command' } ] }

**Comment by justvitalius** [comment]
Проблема была в том, что нет username. А на него все было заточено. Исправлено.

**Comment by justvitalius** [comment]
@GlebSa проверить бы
