### ISSUE TITLE
Нужно определиться с итоговым именем бота, будет ли приветствие при его запуске, иструкция по работе

### ISSUE THREAD

**Issue by w3dip** [justVitalius/quiz-telegram-bot#48]
Нужно ли описывать базовые команды /start /clear. Если он на все ответил уже и пытается сделать /start нужно ли писать что вы уже на все ответили

**Описание и справка**
-вариант1-
Добро пожаловать в telegram опросник от Сбербанк Технологии.

Бот будет присылать вопросы по фронтенду и смежным javascript технологиям. Ваша задача - выбрать один правильный вариант ответа. Любое написанное боту сообщение игнорируется (кроме команд ниже).

Более подробную информацию о призах и правилах проведения можно узнать у hr на стойке Сбербанк Технологии.

-вариант2-
Добро пожаловать!
Бот будет присылать вопросы по frontend и javascript технологиям.
Ваша задача - выбрать один правильный вариант ответа.
Ответ засчитывается только после нажатия на кнопку под вопросом.
Любое написанное боту сообщение игнорируется (кроме досутпных команд).

Дедлайна нет. Ограничений по времени нет (в течение конференции - 2 дня).

Чтобы увидеть список доступных команд введите / и далее система подскажет возможные варианты

**Команды**
start - принять участие в анкетировании
help - справка
clear - начать тестирование заново (сбросит все ответы)

**Comment by justvitalius** [comment]
Действия опишу в дескрипшене. Финальные

**Comment by w3dip** [comment]
Всегда есть люди, придирчиво относящиеся к тексту, если мы рассматриваем ПРы под лупой, то почему так не смотрим на все остальное - в тексте выше видно, что нет запятых, название компании не через тире и т.д. - для меня например это критично, когда пользователь видит что в текстах опечатки - сразу видно отношение

**Comment by justvitalius** [comment]
@w3dip этот текст не финальный. Я вставил два текста сюда, чтобы в итоге получить финал.
Полностью тебя поддерживаю, что текст должен быть корректно составлен.

**Comment by justvitalius** [comment]
Решили на общей встрече, что бот будет называться SbertechHolyJSBot.
Лого готовим, в крайнем случае возьмем обычный логотив СБЕРБАНК-ТЕХНОЛОГИИ.
Текст "About" для бота ждем от hr.

**Comment by justvitalius** [comment]
Сбертех бот.

Доступен во время проведения конференции HolyJS 2018 в Санкт-Петербурге.
Присылает вопросы по фронтенду и смежным javascript технологиям. 

Ваша задача - ответить на все вопросы, попасть в топ участников по количеству правильных ответов и принять участие в главном розыгрыше.
Более подробная информация у сотрудников на стойке Сбертеха. 

Все команды бота доступны по клавише /
